export const INCREMENT_ITEM_CART = "INCREMENT_ITEM_CART";
export const DECREMENT_ITEM_CART = "DECREMENT_ITEM_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const SAVED_CART_DATA = "SAVED_CART_DATA";
